# permissions for end users to edit listeners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: listener-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jobicok8s
    app.kubernetes.io/part-of: jobicok8s
    app.kubernetes.io/managed-by: kustomize
  name: listener-editor-role
rules:
- apiGroups:
  - jobico.coeux.dev
  resources:
  - listeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobico.coeux.dev
  resources:
  - listeners/status
  verbs:
  - get
