FROM golang:1.22.1-bullseye as builder

WORKDIR /workdir

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./cmd/execint/ ./cmd/execint/
RUN go build -o ./bin/ -trimpath ./cmd/...

FROM  debian:12-slim as exec
WORKDIR /app
COPY --from=builder /workdir/bin/* .
ENTRYPOINT ["/app/execint"]