FROM golang:1.22.1-bullseye as builder

WORKDIR /workdir

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./cmd/listener/ ./cmd/listener/
RUN go build -o ./bin/ -trimpath ./cmd/...

FROM  debian:12-slim as listener
WORKDIR /app
COPY --from=builder /workdir/bin/* .
ENTRYPOINT ["/app/listener"]