apiVersion: jobico.coeux.dev/v1
kind: Listener
metadata:
  labels:
    app.kubernetes.io/name: listener
    app.kubernetes.io/instance: listener-sample
    app.kubernetes.io/part-of: jobicok8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: jobicok8s
  name: listener-sample
spec:
  # TODO(user): Add fields here
