resources:
- bases/jobico.coeux.dev_jobs.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
- path: patches/webhook_in_jobs.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

- path: patches/cainjection_in_jobs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
