---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVwakNDQXc2Z0F3SUJBZ0lSQU9TVXdrYU8rbGRKMmRiRTFnK1IrcU13RFFZSktvWklodmNOQVFFTEJRQXcKYXpFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU0F3SGdZRFZRUUxEQmRoYW1OdgpjM1JoUUVSRlUwdFVUMUF0T1ZNelFVWTBRakVuTUNVR0ExVUVBd3dlYld0alpYSjBJR0ZxWTI5emRHRkFSRVZUClMxUlBVQzA1VXpOQlJqUkNNQjRYRFRJME1ETXlOekV6TXpjd05Gb1hEVE0wTURNeU56RXpNemN3TkZvd2F6RWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1TQXdIZ1lEVlFRTERCZGhhbU52YzNSaApRRVJGVTB0VVQxQXRPVk16UVVZMFFqRW5NQ1VHQTFVRUF3d2ViV3RqWlhKMElHRnFZMjl6ZEdGQVJFVlRTMVJQClVDMDVVek5CUmpSQ01JSUJvakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBWThBTUlJQmlnS0NBWUVBckxNSnB6T3UKVlZUMGxFd0tSakMvKzhwODE0RDJpNVN3Q2FzV201NUhDS1VlWU42VWYwWThkT1lra1VsYjhJQU5ndU80TDlpTAp6V2NFeE4wRHNKcWttT05aa0s5M1l6d0JLLzR2Y2ZvKzBuV2dzRDd0ajk0VjZPOXZsWmt6NGpETlY4NDhqUkluCmNwVFBJRmV1YlErZ2ZDMXF5R1BkWk9uVG5RZFVzUHpmdE5YdHZxMkZvdnUvK2hXTXhsYU1rSEh1dlQ5dTN0eTYKeEZkczJqUE9wSWdUVVg2elFRTUZ5cGpTSWl0bzdFQlhkZzNTUyttNytFZ0Zld2ZQMlR2N0N4T0hNbVFSeG1CNgpvN0dydWJvV1JJQ2o2dGRrd3RQRGcrbmt1Qy9FeEQ3WmJZVWd3TTJjS0FrbVk5bjN2aFpTU3NZOWZhRTBHTGJ1CjdkNWdmdFpTMWhyUlM0ekVEaDJDdituaG9LbDdZaHp5c3dpTlJPU2Z3aHZvdXNWc2c4aUxJcEovUUJSekMxMysKM0NFQS91WDVkWXZON2Q3TGlWMnhqWXNXUGU5ek44VHlrcnMyc09nK3ZmRWZFQ0RkQ1N6eHRqcjlFaWF1R2pyWAppTzZGL1ZQZ0lZZVRyTHQ5aTFLbW5uMGFYWlA2MmlHUGZYaitxMjR5RFNkMmxuYXdVRUJJa29oMUFnTUJBQUdqClJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQ0JEQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVcKQkJTWmxaam1DNUZzUXMvRndqc3JZWWNJUE9NM0lqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FZRUFDWFdsK0gragpCZVBvUlhBOTF0d2hLV2dvdHZiYmhoU1RsQXdybjdIUXlzek9vci9RN3pZdFkrd0VZSW5PeE95NEJyZ1JnUUZ6ClFsSU1Rc1VlTUlaSmxLL2hYZDNETDVSL1BYQ1RxdzhBMkE1STRRTmYvTklLZnFMcG9VOUIzb2NXdDJQdWRBcSsKNmlNM2hGQzBYT0JCL0pWeGFYcmdGV3Q0OSt2ejVtWFVjN1dMQUZ0R095Ti85UDQxYzBoVldWZys3S21xK0RYMAprd0w5MlBNM2JxU1gvdDcyS2ZLT01rSzNXS1QwUjFXa1dOTTRYd0hoWTNMTFMrRTVGM3Q4ZURibDh3bTVTYlJGCnliNDIrMkhMblIyK2xUVjloNEl4akcwSlNkMUd6VGQrTndnRE1xWDJJcWZjdThrN3hpRm0vK3N6YjdFRlVPbmwKaU5FeVNGcVAzYStOWnVuM1NPWWQvRHJVTGcwN3dxMGFpRk80dWUwVmxhZG9FTzY5VytOVitoMHVMZVdRNmw5SAprd2FlM3J5VXduUElFT01IK2JGVDNFczVPN1FZSHlQWnJoNzUvQnJFY2JNQThuWWlDQ254Zm0zZXFoV3dRSkZICkJKZDVlWjFsNFpMVktEaXp5My9vME9QeGFBRVROaENaRmFQa1dIT2duaHpUMmpKYk5YcG9INE1TCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    url: https://172.17.0.1:9443/validate-jobico-coeux-dev-v1-job
  failurePolicy: Fail
  name: mjob.kb.io
  rules:
  - apiGroups:
    - jobico.coeux.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVwakNDQXc2Z0F3SUJBZ0lSQU9TVXdrYU8rbGRKMmRiRTFnK1IrcU13RFFZSktvWklodmNOQVFFTEJRQXcKYXpFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU0F3SGdZRFZRUUxEQmRoYW1OdgpjM1JoUUVSRlUwdFVUMUF0T1ZNelFVWTBRakVuTUNVR0ExVUVBd3dlYld0alpYSjBJR0ZxWTI5emRHRkFSRVZUClMxUlBVQzA1VXpOQlJqUkNNQjRYRFRJME1ETXlOekV6TXpjd05Gb1hEVE0wTURNeU56RXpNemN3TkZvd2F6RWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1TQXdIZ1lEVlFRTERCZGhhbU52YzNSaApRRVJGVTB0VVQxQXRPVk16UVVZMFFqRW5NQ1VHQTFVRUF3d2ViV3RqWlhKMElHRnFZMjl6ZEdGQVJFVlRTMVJQClVDMDVVek5CUmpSQ01JSUJvakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBWThBTUlJQmlnS0NBWUVBckxNSnB6T3UKVlZUMGxFd0tSakMvKzhwODE0RDJpNVN3Q2FzV201NUhDS1VlWU42VWYwWThkT1lra1VsYjhJQU5ndU80TDlpTAp6V2NFeE4wRHNKcWttT05aa0s5M1l6d0JLLzR2Y2ZvKzBuV2dzRDd0ajk0VjZPOXZsWmt6NGpETlY4NDhqUkluCmNwVFBJRmV1YlErZ2ZDMXF5R1BkWk9uVG5RZFVzUHpmdE5YdHZxMkZvdnUvK2hXTXhsYU1rSEh1dlQ5dTN0eTYKeEZkczJqUE9wSWdUVVg2elFRTUZ5cGpTSWl0bzdFQlhkZzNTUyttNytFZ0Zld2ZQMlR2N0N4T0hNbVFSeG1CNgpvN0dydWJvV1JJQ2o2dGRrd3RQRGcrbmt1Qy9FeEQ3WmJZVWd3TTJjS0FrbVk5bjN2aFpTU3NZOWZhRTBHTGJ1CjdkNWdmdFpTMWhyUlM0ekVEaDJDdituaG9LbDdZaHp5c3dpTlJPU2Z3aHZvdXNWc2c4aUxJcEovUUJSekMxMysKM0NFQS91WDVkWXZON2Q3TGlWMnhqWXNXUGU5ek44VHlrcnMyc09nK3ZmRWZFQ0RkQ1N6eHRqcjlFaWF1R2pyWAppTzZGL1ZQZ0lZZVRyTHQ5aTFLbW5uMGFYWlA2MmlHUGZYaitxMjR5RFNkMmxuYXdVRUJJa29oMUFnTUJBQUdqClJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQ0JEQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVcKQkJTWmxaam1DNUZzUXMvRndqc3JZWWNJUE9NM0lqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FZRUFDWFdsK0gragpCZVBvUlhBOTF0d2hLV2dvdHZiYmhoU1RsQXdybjdIUXlzek9vci9RN3pZdFkrd0VZSW5PeE95NEJyZ1JnUUZ6ClFsSU1Rc1VlTUlaSmxLL2hYZDNETDVSL1BYQ1RxdzhBMkE1STRRTmYvTklLZnFMcG9VOUIzb2NXdDJQdWRBcSsKNmlNM2hGQzBYT0JCL0pWeGFYcmdGV3Q0OSt2ejVtWFVjN1dMQUZ0R095Ti85UDQxYzBoVldWZys3S21xK0RYMAprd0w5MlBNM2JxU1gvdDcyS2ZLT01rSzNXS1QwUjFXa1dOTTRYd0hoWTNMTFMrRTVGM3Q4ZURibDh3bTVTYlJGCnliNDIrMkhMblIyK2xUVjloNEl4akcwSlNkMUd6VGQrTndnRE1xWDJJcWZjdThrN3hpRm0vK3N6YjdFRlVPbmwKaU5FeVNGcVAzYStOWnVuM1NPWWQvRHJVTGcwN3dxMGFpRk80dWUwVmxhZG9FTzY5VytOVitoMHVMZVdRNmw5SAprd2FlM3J5VXduUElFT01IK2JGVDNFczVPN1FZSHlQWnJoNzUvQnJFY2JNQThuWWlDQ254Zm0zZXFoV3dRSkZICkJKZDVlWjFsNFpMVktEaXp5My9vME9QeGFBRVROaENaRmFQa1dIT2duaHpUMmpKYk5YcG9INE1TCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    url: https://172.17.0.1:9443/validate-jobico-coeux-dev-v1-job
  failurePolicy: Fail
  name: vjob.kb.io
  rules:
  - apiGroups:
    - jobico.coeux.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
  sideEffects: None
